---
# Configuración de Gateway Debian: IP forwarding, NAT (nftables), DHCP/DNS (dnsmasq)

- name: Instalar paquetes requeridos (dnsmasq, nftables)
  apt:
    name:
      - dnsmasq
      - nftables
    state: present
    update_cache: true
  tags: ["router", "packages"]

- name: Habilitar IP forwarding IPv4 de forma persistente
  copy:
    dest: /etc/sysctl.d/99-router.conf
    content: |
      net.ipv4.ip_forward = 1
    owner: root
    group: root
    mode: '0644'
  notify: aplicar-sysctl
  tags: ["router", "ipforward"]

- name: Aplicar sysctl inmediatamente
  command: sysctl -w net.ipv4.ip_forward=1
  changed_when: false
  tags: ["router", "ipforward"]

- name: Desplegar configuración de nftables con NAT
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  notify: recargar-nftables
  tags: ["router", "nat", "firewall"]

- name: Asegurar servicio nftables habilitado y activo
  systemd:
    name: nftables
    state: started
    enabled: true
  tags: ["router", "nat", "firewall"]

- name: Configurar dnsmasq (DHCP y DNS)
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/99-lab.conf
    owner: root
    group: root
    mode: '0644'
  notify: reiniciar-dnsmasq
  tags: ["router", "dhcp", "dns"]

- name: Asegurar servicio dnsmasq habilitado y activo
  systemd:
    name: dnsmasq
    state: started
    enabled: true
  tags: ["router", "dhcp", "dns"]
