---
# Handlers para debian_router

- name: aplicar-sysctl
  command: sysctl --system
  changed_when: false

- name: recargar-nftables
  systemd:
    name: nftables
    state: restarted

- name: reiniciar-dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: aplicar-red
  command: /sbin/ifup {{ router_internal_interface }}
  changed_when: false

- name: reiniciar-networkd
  systemd:
    name: systemd-networkd
    state: restarted
